spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_name
    username: your_username
    password: your_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
